In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
for i in np.array(my_list):
    print(i)

1
2
3


In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
for i in np.array(my_matrix):
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [11]:
np.ones((1,1))

array([[ 1.]])

In [12]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [14]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
np.random.rand(2)

array([ 0.58087269,  0.22883212])

In [17]:
np.random.rand(5,5)

array([[ 0.37173665,  0.72943955,  0.7234871 ,  0.01116772,  0.45184398],
       [ 0.77050818,  0.25491495,  0.55285747,  0.51453785,  0.34201989],
       [ 0.21427759,  0.77182543,  0.2276843 ,  0.58351908,  0.52840635],
       [ 0.5520543 ,  0.64973979,  0.72537054,  0.53494016,  0.97485755],
       [ 0.55422063,  0.53710218,  0.01567599,  0.94751836,  0.42478284]])

In [18]:
np.random.randn(2)

array([ 0.02425689,  0.96570966])

In [19]:
np.random.randn(5,5)

array([[-1.06497243, -0.06642881, -1.36879909,  2.19759784,  1.05414121],
       [-1.29696924,  0.65006664, -2.02896175,  0.58233813,  0.12188898],
       [-2.80476574,  0.35104745, -0.58900267, -1.0772569 , -0.7828618 ],
       [ 1.40506812, -0.83365994,  1.42205047,  0.70875228,  0.50199529],
       [-1.27395258,  0.66879097, -1.07137081, -0.55216052,  0.45194333]])

In [20]:
np.random.randint(5)

4

In [21]:
np.random.randint(0,100,10)

array([58, 78, 47, 15, 87, 99, 83, 56, 65, 96])

In [22]:
arr = np.arange(25)

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([31, 47, 15, 18, 12, 11, 41,  1, 22, 40])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

47

In [28]:
ranarr.argmax()

1

In [29]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [31]:
bool_arr = arr > 4

In [32]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [34]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# Pandas

In [38]:
import numpy as np
import pandas as pd

In [39]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [40]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [41]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [42]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [43]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [44]:
ser1 = pd.Series([1,2,3,4],index= ['USA','GERMANY','USSR','JAPAN'])
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [45]:
# pandas_dataframes

In [46]:
import pandas as pd
import numpy as np

In [47]:
from numpy.random import randn
np.random.seed(101)

In [48]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(),columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [50]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [51]:
df['Sum'] = df['W'] + df['Y']

In [52]:
df

W         X         Y         Z       Sum
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [53]:
df.drop('Sum',axis = 1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [54]:
df

W         X         Y         Z       Sum
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [55]:
df.drop('Sum',axis = 1,inplace=True)

In [56]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [58]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [59]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [60]:
df.loc['B','Y']

-0.84807698340363147

In [61]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [62]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [63]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [64]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [66]:
newind = 'CA NY WY OR CO'.split()
df['States'] = newind

In [67]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [68]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [69]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [70]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [71]:
df = pd.DataFrame(np.random.randn(6,2),index = hier_index, columns = ['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [72]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [73]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [81]:
df.xs('G1')

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [82]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [87]:
df.index.names = ['Group','Num']

In [88]:
df.xs(1,level='Num')

A         B
Group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

In [89]:
# pandas_missing_data

In [90]:
import numpy as np
import pandas as pd

In [91]:
df = pd.DataFrame({
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]
})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [92]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [93]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [94]:
df.dropna(thresh = 2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [95]:
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [96]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [97]:
# pandas_group_by

In [98]:
import pandas as pd

In [99]:
data = {
    'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]
}
df = pd.DataFrame(data)

In [100]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [101]:
by_comp = df.groupby('Company')
by_comp

In [102]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [103]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [104]:
by_comp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [106]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [109]:
by_comp

In [113]:
by_comp.describe().loc['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

In [114]:
# pandas merging joining and concatenating

In [115]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [116]:
pd.merge(left,right,on = ['key1','key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [118]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [119]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [117]:
pd.merge(left,right,how='outer', on = ['key1','key2'])

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [120]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [121]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [122]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [123]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [124]:
left.join(right,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [125]:
# pandas operations

In [127]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [128]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [129]:
df['col2'].nunique()

3

In [130]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [131]:
newdf = df[(df['col1']>2) & (df['col2'] == 444)]
newdf

col1  col2 col3
3     4   444  xyz

In [132]:
df['col1'].sum()

10

In [133]:
df.sort_values(by='col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [134]:
# pandas data input and output

In [135]:
import numpy as np
import pandas as pd

In [139]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')


In [141]:
df[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc